kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world

steps:
- name: upload
  image: plugins/s3
  settings:
    bucket: drone-bucket-8
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: public/**/*
    target: /
